const SRX_ARCHIVE_ASSET_BASE = "https://raw.githubusercontent.com/HeartlessN3ko/realm-assets/main/";

function srxAsset(path, alt) {
  return {
    path,
    alt,
    remote: SRX_ARCHIVE_ASSET_BASE + encodeURI(path),
  };
}

function noImage(status = "No authenticated public image is held for this record.") {
  return { image: null, imageStatus: status };
}

window.SRX_PUBLIC_ARCHIVE = {
  updated: "June 30, 2026",
  currentEra: "3120 CE",
  directories: [
    {
      id: "world",
      label: "World Record",
      description: "Verified public scholarship concerning Terra, the Nexus, ancient peoples, and the Rift.",
      href: "knowledge/",
      image: srxAsset("maps/region-map-of-terra.png", "Regional survey map of Terra."),
    },
    {
      id: "places",
      label: "Geographic Intelligence",
      description: "Authenticated surveys of cities, territories, districts, transit systems, and significant sites.",
      href: "places/",
      image: srxAsset("maps/midgar-overhead.png", "Authenticated overhead survey of Midgar."),
    },
    {
      id: "institutions",
      label: "Governments & Organizations",
      description: "Public assessments of governments, agencies, guilds, sovereign orders, and recognized powers.",
      href: "institutions/",
      image: srxAsset("logos/SRX-Logo-New.png", "Official mark of Shinra Robotics and Xenogenetics."),
    },
    {
      id: "history",
      label: "Historical Archive",
      description: "Dated events reconstructed from surviving records and authorized declassifications.",
      href: "history/",
      image: srxAsset("oracle/historical/09-treaty-of-ceasefire.png", "Authenticated archive image of the Treaty of Ceasefire."),
    },
    {
      id: "people",
      label: "People of Record",
      description: "Public service histories, executive records, memorials, and notable foreign persons.",
      href: "bios/",
      image: srxAsset("npc/arthas-raiku.png", "Official portrait of President Arthas Raiku."),
    },
  ],
  categories: [
    { id: "world", label: "World Record", description: "Public scholarship and planetary reference." },
    { id: "places", label: "Geographic Intelligence", description: "Verified places and territorial surveys." },
    { id: "institutions", label: "Governments & Organizations", description: "Institutional and diplomatic assessments." },
    { id: "history", label: "Historical Archive", description: "Dated and declassified historical records." },
    { id: "people", label: "People of Record", description: "Public biographical and service records." },
  ],
  records: [
    {
      id: "the-realm",
      directories: ["world"], category: "world", title: "The Realm and the Nexus", subtitle: "Terra's place within the connected realities",
      classification: "Open Scholarly Record",
      image: srxAsset("maps/region-map-of-terra.png", "Regional survey map of Terra, the inhabited center of the Realm."),
      summary: "The Realm is the multidimensional network surrounding Terra, a world positioned at the central junction of many realities.",
      body: [
        "Terra is the primary inhabited world of the Nexus. Its history has been shaped by repeated contact with other realities, most dramatically during the Great Rift, when dimensional boundaries failed across the planet.",
        "Modern dimensional movement is not limited to catastrophe. Stable corridors, naturally occurring passages, and the Shinra Gateway all connect Terra to locations beyond its native reality. Ordinary travel within Terra remains distinct from interdimensional transit.",
        "No accepted scholarship has identified an outer boundary to the Realm. SRX therefore treats the Nexus as an open system: mapped in part, inhabited beyond current measure, and capable of producing conditions for which no local precedent exists.",
      ],
      facts: [["Central World", "Terra"], ["Known Structure", "Multidimensional network"], ["Primary Modern Gateway", "Shinra Gateway"], ["Current Year", "3120 CE"]],
      highlights: ["Terra predates the Great Rift.", "Dimensional arrivals are now recorded under stabilized transit protocols.", "The full extent of the Nexus remains unknown."],
      related: ["terra", "great-rift", "gateway-station"], source: "data/lore/world_lore.md",
    },
    {
      id: "terra",
      directories: ["world", "places"], category: "world", title: "Terra", subtitle: "Nexus world and seat of modern Realm civilization",
      classification: "Open Planetary Record",
      image: srxAsset("maps/topography-map-of-terra.png", "Topographical survey of Terra."),
      summary: "Terra is an ancient, populous world orbiting the binary stars Sol and Aeon and divided among six major continental regions.",
      body: [
        "Terra was inhabited long before the arrival of Rift-displaced populations. The oldest surviving traditions attribute its formation to the Coders and identify it as the original home of the Ai Codian peoples.",
        "The planet now supports thousands of cultures and species. Ancient ruins, modern cities, magical territories, industrial states, and lands permanently altered by dimensional collision exist within the same geographic system.",
        "Modern population records place Terra near 3.2 billion residents. That figure remains approximate because several sovereign regions do not share census data and some communities cannot be measured by conventional means.",
      ],
      facts: [["Star System", "Sol-Aeon binary"], ["Major Regions", "Six continental regions"], ["Estimated Population", "Approximately 3.2 billion"], ["Largest Shinra City", "Midgar"]],
      highlights: ["Terra's native history extends far beyond recorded modern government.", "Several pre-Rift peoples survive through mixed bloodlines.", "Large areas remain politically or physically inaccessible."],
      related: ["the-realm", "ai-codians", "continental-survey"], source: "data/lore/world_lore.md",
    },
    {
      id: "ai-codians",
      directories: ["world"], category: "world", title: "The Ai Codian Peoples", subtitle: "The oldest recorded civilizations of Terra",
      classification: "Open Scholarly Record", ...noImage(),
      summary: "Ai Codians are recognized as Terra's first known sentient peoples and the builders of its earliest great civilizations.",
      body: [
        "Seven principal Ai Codian lineages are recorded: Gaians, Etherians, Oakans, Aquians, Lunarians, Pyrians, and Chronians. Their civilizations produced the Stone Halls, Grand Archive, Great Groves, Coral Throne, Forge Eternal, Moonspire, and Temporal Archive.",
        "The Great Rift and the thousand years of war that followed destroyed most Ai Codian population centers. Intermarriage with displaced peoples then carried their ancestry into later bloodlines across Terra.",
        "Fullblood communities are exceptionally rare in 3120 CE. The best documented surviving community is located at Everlasting City in West-Erdanis, while mixed descendants are present throughout the planet.",
      ],
      facts: [["Recorded Lineages", "Seven"], ["Earliest Civilization", "Pre-Rift Terra"], ["Known Fullblood Community", "Everlasting City"], ["Present Status", "Rare; widely dispersed ancestry"]],
      highlights: ["Much of their written knowledge was lost during the 1,000-Year War.", "Modern magical and cultural traditions preserve fragments of Ai Codian practice.", "Chronian scholarship is considered almost entirely lost."],
      related: ["terra", "great-rift", "thousand-year-war"], source: "data/lore/world_lore.md",
    },
    {
      id: "coders-and-source-code",
      directories: ["world"], category: "world", title: "Coders and the Source Code", subtitle: "The oldest surviving account of creation",
      classification: "Open Scholarly Record", ...noImage("No authenticated depiction exists; surviving material is textual and ceremonial."),
      summary: "The oldest Ai Codian traditions describe the Coders as the first conscious beings and the Source Code as the structure from which reality was formed.",
      body: [
        "According to surviving doctrine, the Coders used the Code of Creation to form Terra and later appointed Guardians to preserve balance within the Nexus. The same tradition holds that Ai Codians were created through the Code rather than through ordinary biological origin.",
        "The Coders are said to have withdrawn from direct contact approximately one hundred thousand years before the Great Rift. No modern institution has produced verifiable evidence of direct communication since that withdrawal.",
        "SRX distinguishes recorded belief from demonstrated mechanism. Source Code phenomena are documented, but the theological claims surrounding their origin remain subjects of scholarship rather than settled operational fact.",
      ],
      facts: [["Primary Tradition", "Ai Codian creation accounts"], ["Associated Concept", "Code of Creation"], ["Last Claimed Direct Contact", "Approximately 100,000 BR"], ["Modern Status", "Unverified at origin"]],
      highlights: ["The Source Code is treated as both a religious and technical concept.", "Guardian traditions differ sharply across surviving cultures.", "No public record claims certainty regarding the Coders' present state."],
      related: ["ai-codians", "the-realm", "great-rift"], source: "data/lore/world_lore.md",
    },
    {
      id: "continental-survey",
      directories: ["places", "world"], category: "places", title: "Continental Survey of Terra", subtitle: "Six major regions and their established powers",
      classification: "Open Geographic Survey",
      image: srxAsset("maps/map-of-country-terrotories..png", "Political and territorial survey map of Terra."),
      summary: "Modern geography divides Terra into East-Erdanis, West-Erdanis, Eflinden, the Wasteland Continent, the Western Continent, and the Isles of Terra.",
      body: [
        "East-Erdanis contains Midgar, Junon, Coral City, Ciel Castle, and several Shinra-controlled military and civilian sites. West-Erdanis includes Cerium, Everlasting City, and surviving Ai Codian centers.",
        "Eflinden contains Silvermoon and other historic elven territories. The Wasteland Continent is dominated by Cameron City and the Realm Inspection Agency. The far western island of Cubax contains Kantonia, formerly Valhalla City.",
        "The Isles of Terra include Tartanalia and DragonsKeep Island. Political boundaries remain less stable than geography; treaty zones, sovereign cities, and territories concealed by magic complicate any single map.",
      ],
      facts: [["Major Regions", "Six"], ["Shinra Capital", "Midgar, East-Erdanis"], ["RIA Capital", "Cameron City, Wasteland Continent"], ["Independent Treaty Zone", "DragonsKeep Island"]],
      highlights: ["Maps reflect verified access, not universal jurisdiction.", "Some borders are enforced by magic rather than conventional military control.", "Population estimates vary sharply outside participating census territories."],
      related: ["terra", "midgar", "cameron-city", "dragonskeep"], source: "data/lore/world_lore.md",
    },
    {
      id: "midgar",
      directories: ["places"], category: "places", title: "Midgar", subtitle: "Capital of the Shinra Kingdom",
      classification: "Open Civic Record",
      image: srxAsset("maps/midgar-overhead.png", "Authenticated overhead survey of Midgar and its eight-sector plate structure."),
      summary: "Midgar is an eight-sector plate city in East-Erdanis, home to approximately 350 million residents and the seat of Shinra government.",
      body: [
        "Eight numbered sectors surround Sector 0 and Shinra Tower. Odd-numbered sectors occupy the open-sky lower plate; even-numbered sectors are enclosed within the upper structure.",
        "A retractable titanium-steel defense plate shields the city from the center outward. Surveillance, traffic control, public infrastructure, and interdimensional intake are coordinated through SRX systems.",
        "Security presence varies by district. Sector 0, the military sector, and research districts operate under the strongest controls, while commercial and recreation sectors permit greater civilian movement.",
      ],
      facts: [["Region", "East-Erdanis"], ["Population", "Approximately 350 million"], ["City Structure", "Eight sectors around Sector 0"], ["Governing Authority", "Shinra Kingdom"]],
      highlights: ["Founded approximately 2870 CE.", "The plate and tower were expanded over several generations.", "SRX operates the city's major defensive and transit systems."],
      related: ["lower-plate", "upper-plate", "shinra-tower", "shinra-kingdom"], source: "data/srx_database/locations/MIDGAR.md",
    },
    {
      id: "lower-plate",
      directories: ["places"], category: "places", title: "Midgar Lower Plate", subtitle: "Open-sky sectors 1, 3, 5, and 7",
      classification: "Open Civic Record",
      image: srxAsset("locations/lower-plate-train_station.png", "Lower-plate transit station serving Midgar's open-sky sectors."),
      summary: "The lower plate contains Midgar's financial, commercial, residential, and recreation districts.",
      body: [
        "Sector 1 is the Financial District; Sector 3 is the Commercial District; Sector 5 contains managed residential housing; Sector 7 serves as the principal recreation and cultural district.",
        "These sectors remain open to the sky but can be protected behind the city's blast wall. SRX presence is strongest in Sector 1 and decreases toward Sector 7.",
        "Sector 3 Market Street and the Sector 5 Residential District are among the most heavily used civilian destinations for residents entering the city through official channels.",
      ],
      facts: [["Sectors", "1, 3, 5, 7"], ["Primary Use", "Civilian life and commerce"], ["Sky Access", "Open"], ["Transit", "Lower-plate rail network"]],
      highlights: ["Sector identity determines services and security posture.", "Commercial activity is concentrated in Sector 3.", "Residential intake housing is concentrated in Sector 5."],
      related: ["midgar", "upper-plate", "residential-district"], source: "data/srx_database/locations/LOWER_PLATE.md",
    },
    {
      id: "upper-plate",
      directories: ["places"], category: "places", title: "Midgar Upper Plate", subtitle: "Enclosed sectors 2, 4, 6, and 8",
      classification: "Open Civic Record",
      image: srxAsset("locations/upper-plate-train_station.png", "Upper-plate transit station serving Midgar's enclosed sectors."),
      summary: "The upper plate contains Midgar's industrial, military, entertainment, and research districts.",
      body: [
        "Sector 2 houses industry and energy control; Sector 4 is reserved for military operations; Sector 6 contains Wall Market and the principal entertainment district; Sector 8 houses corporate and research facilities.",
        "The upper plate is roofed, climate-managed, and structurally hardened. Civilian access is unrestricted in designated areas of Sectors 2 and 6 but controlled in the military and research sectors.",
        "Sector 6 is subject to a lighter routine security posture than other upper sectors. Sector 4 and Sector 8 operate under permanent access controls.",
      ],
      facts: [["Sectors", "2, 4, 6, 8"], ["Primary Use", "Industry, defense, entertainment, research"], ["Environment", "Enclosed and climate-managed"], ["Restricted Sectors", "4 and 8"]],
      highlights: ["Sector 4 contains SRX military staging areas.", "Sector 6 supports a tolerated gray economy.", "Sector 8 contains prototype and data facilities."],
      related: ["midgar", "lower-plate", "shinra-tower"], source: "data/srx_database/locations/UPPER_PLATE.md",
    },
    {
      id: "gateway-station",
      directories: ["places", "institutions"], category: "places", title: "Gateway Station", subtitle: "Midgar interdimensional arrival facility",
      classification: "Open Arrival Record",
      image: srxAsset("locations/onboarding_room.png", "SRX arrival-processing hall within the Gateway intake system."),
      summary: "Gateway Station registers and processes interdimensional arrivals entering the Shinra Kingdom through the stabilized Rift corridor.",
      body: [
        "The public intake hall is located within the Sector 0 complex. Arrival processing includes identity registration, medical examination, ability assessment, monitor issuance, and assignment under the Limiter Protocol.",
        "The stabilized portal is located on the southern islands near DragonsKeep. It is monitored continuously and protected as critical dimensional infrastructure.",
        "The Gateway is not used for ordinary movement by Terra residents. Its purpose is controlled interdimensional transit and the safe reception of displaced populations.",
      ],
      facts: [["Public Facility", "Sector 0 intake hall"], ["Portal Region", "Southern islands"], ["Operating Authority", "SRX"], ["Status", "Operational"]],
      highlights: ["Arrival records are attached to a permanent SRX identity.", "Transit is monitored continuously.", "Unstable or hostile arrivals are diverted from civilian processing."],
      related: ["the-realm", "midgar", "srx"], source: "data/srx_database/locations/GATEWAY_STATION.md",
    },
    {
      id: "shinra-tower",
      directories: ["places", "institutions"], category: "places", title: "Shinra Tower", subtitle: "Seat of government and SRX headquarters",
      classification: "Open Civic Record",
      image: srxAsset("reference/shinra-tower-info-shots.png", "Public information display documenting Shinra Tower and its principal zones."),
      summary: "Shinra Tower occupies Sector 0 at the center of Midgar and houses both the Kingdom government and SRX command.",
      body: [
        "Floors 1 through 45 contain public offices, exhibits, shops, and archive services. Higher floors contain training, operations, research, and executive departments subject to increasing clearance requirements.",
        "The seventieth floor contains the presidential office. The surrounding grounds include four memorial monuments honoring figures associated with the construction and preservation of modern Shinra.",
        "The Tower coordinates public administration, defense, research, and city infrastructure. Access restrictions are enforced by floor, department, and operational need.",
      ],
      facts: [["Location", "Sector 0, Midgar"], ["Public Floors", "1-45"], ["Executive Office", "Floor 70"], ["Authority", "Shinra Kingdom / SRX"]],
      highlights: ["The grounds serve both administrative and memorial functions.", "SRX Operations occupies restricted upper floors.", "Sublevel access is not included in public building tours."],
      related: ["midgar", "srx", "shinra-kingdom", "arthas-raiku"], source: "data/srx_database/locations/SHINRA_TOWER.md",
    },
    {
      id: "residential-district",
      directories: ["places"], category: "places", title: "Sector 5 Residential District", subtitle: "Managed civilian housing on the lower plate",
      classification: "Open Civic Record",
      image: srxAsset("locations/dorm_lobby.png", "Residential lobby serving Sector 5 managed housing."),
      summary: "Sector 5 contains Midgar's principal managed housing blocks and the standard residential placement for registered arrivals.",
      body: [
        "The district includes the Residential Hub, Community Commons, service offices, private dormitories, and the central Residential Lobby. Public design emphasizes calm movement, accessible services, and stable community use.",
        "SRX maintains a moderate security presence integrated into normal civic systems. Crime remains low relative to the commercial and entertainment sectors.",
        "Housing assignments, city identification, and remaining arrival documentation are administered through district service offices.",
      ],
      facts: [["Sector", "5"], ["Plate", "Lower"], ["Primary Function", "Civilian housing"], ["Security Posture", "Moderate"]],
      highlights: ["The district is open to registered residents.", "Community facilities operate around the Residential Lobby.", "Transit connects directly to the lower-plate rail network."],
      related: ["lower-plate", "gateway-station", "midgar"], source: "data/srx_database/locations/RESIDENTIAL_DISTRICT.md",
    },
    {
      id: "cameron-city",
      directories: ["places", "institutions"], category: "places", title: "Cameron City", subtitle: "Capital of the Realm Inspection Agency",
      classification: "Foreign Civic Assessment",
      image: srxAsset("oracle/grand-library-seed/05-brochure-cameron-city.png", "Authenticated public survey image of Cameron City."),
      summary: "Cameron City is the principal city of the Wasteland Continent and the sovereign seat of the Realm Inspection Agency.",
      body: [
        "The city supports a dense road and waterway network and a population estimated between sixty and one hundred fifty million. Conflicting estimates reflect limited census exchange between sovereign authorities.",
        "RIA headquarters dominates the central skyline. The city also supports veterans, displaced populations outside Shinra jurisdiction, independent scholars, and commercial networks trading information unavailable in Midgar.",
        "Cameron City remains outside Kingdom authority. Travel is governed by the 3088 CE ceasefire and the laws of the Realm Inspection Agency.",
      ],
      facts: [["Region", "Wasteland Continent"], ["Governing Authority", "Realm Inspection Agency"], ["Estimated Population", "60-150 million"], ["Diplomatic Status", "Sovereign under ceasefire"]],
      highlights: ["Shinra law does not apply within Cameron City.", "The RIA remains the city's principal security authority.", "Diplomatic relations remain functional and guarded."],
      related: ["ria", "treaty-of-ceasefire", "continental-survey"], source: "data/srx_database/locations/CAMERON_CITY.md",
    },
    {
      id: "tartan-crater",
      directories: ["places"], category: "places", title: "Tartan Crater", subtitle: "Known site of Terra's major Eternium deposit",
      classification: "Controlled Geographic Summary", ...noImage("No current public survey image has been authenticated for unrestricted release."),
      summary: "Tartan Crater lies within Tartanalia and contains the only confirmed major deposit of Eternium known to modern SRX records.",
      body: [
        "Eternium forms where sustained magical activity alters the surrounding environment over thousands of years. Tartanalia's long Lunarian history produced the conditions required for the deposit beneath the crater.",
        "Ancient elven records identify the formation as the Eternium Crystal. Chronian orders are believed to have guarded it before the destruction of their major institutions.",
        "The site became the center of armed conflict between 3098 and 3108 CE. Access, extraction, and military detail remain controlled under postwar agreements.",
      ],
      facts: [["Region", "Tartanalia"], ["Known Material", "Eternium"], ["Barrier Failure", "3013 CE"], ["Access", "Controlled"]],
      highlights: ["Eternium can channel extraordinary magical energy.", "The deposit has historic religious and strategic significance.", "The crater is not open for civilian excavation."],
      related: ["battle-for-eternium", "continental-survey", "dragonskeep"], source: "data/srx_database/locations/ETERNIUM.md",
    },
    {
      id: "dragonskeep",
      directories: ["places", "institutions"], category: "places", title: "Dragon's Keep", subtitle: "Independent treaty zone of the Weyr",
      classification: "Diplomatic Geographic Record", ...noImage("The archive holds no unrestricted authenticated exterior survey."),
      summary: "Dragon's Keep is a cliffside fortress on DragonsKeep Island and the sovereign sanctuary of the Weyr of Dragonlords.",
      body: [
        "The island lies among the Isles of Terra near Tartanalia. The Keep is governed by Nexa Rei and protected under treaty as neutral ground outside Shinra and RIA jurisdiction.",
        "Entry requires authorization from the Weyr. Historic gatherings at the Keep have imposed ceasefire conditions on rival governments and military organizations.",
        "The site's neutrality is recognized by Shinra. SRX personnel entering the treaty zone remain subject to Weyr authority for the duration of their visit.",
      ],
      facts: [["Region", "Isles of Terra"], ["Sovereign Authority", "Weyr of Dragonlords"], ["Presiding Official", "Nexa Rei"], ["Status", "Independent treaty zone"]],
      highlights: ["The Keep is not Shinra territory.", "Armed political conflict is prohibited on its grounds.", "Access is granted by the Weyr, not by SRX."],
      related: ["weyr-of-dragonlords", "continental-survey", "tartan-crater"], source: "data/srx_database/factions/WEYR_OF_DRAGONLORDS.md",
    },
    {
      id: "srx",
      directories: ["institutions"], category: "institutions", title: "Shinra Robotics and Xenogenetics", subtitle: "Military and technological arm of the Shinra Kingdom",
      classification: "Official Institutional Record",
      image: srxAsset("logos/SRX-Logo-New.png", "Official mark of Shinra Robotics and Xenogenetics."),
      summary: "Shinra Robotics and Xenogenetics administers Midgar's defense, dimensional intake, advanced research, and critical infrastructure.",
      body: [
        "SRX was founded in 3078 CE during the conflict with the Realm Inspection Agency. The organization later became the unified military and technological authority of the Shinra government.",
        "Its principal departments oversee robotics, medicine, xenogenetics, weapons development, public security, Gateway operations, ability calibration, and the Limiter Protocol.",
        "SRX is commanded by the President of the Shinra Kingdom. Its stated institutional mission is that no person under Shinra protection should be left defenseless.",
      ],
      facts: [["Founded", "3078 CE"], ["Headquarters", "Shinra Tower, Midgar"], ["Commander", "President Arthas Raiku"], ["Historic Name", "Shinra Resurrected X"]],
      highlights: ["SRX operates as a state institution, not a private military contractor.", "Gateway intake and city defense fall under the same command authority.", "Research publication is governed by security classification."],
      related: ["shinra-kingdom", "midgar", "gateway-station", "arthas-raiku"], source: "data/srx_database/factions/SRX.md",
    },
    {
      id: "shinra-kingdom",
      directories: ["institutions"], category: "institutions", title: "Shinra Kingdom", subtitle: "Government of Midgar and surrounding territories",
      classification: "Official Government Record",
      image: srxAsset("logos/shinra-gunmetal-logo.png", "Official crest of the Shinra Kingdom."),
      summary: "The Shinra Kingdom governs Midgar and its recognized territories through a presidency transferred by succession.",
      body: [
        "The President serves as head of state and commander of SRX. The Vice President administers the civilian government, including departments, municipal offices, and public services.",
        "The present state developed from the Republic of Shinra during the reconstruction that followed the Battle for Eternium. Government and military authority were consolidated into one command structure.",
        "President Arthas Raiku assumed office in 3120 CE. Vice President Alexander Raiku, the preceding president, remains responsible for civilian administration.",
      ],
      facts: [["Capital", "Midgar"], ["Seat", "Shinra Tower"], ["President", "Arthas Raiku"], ["Vice President", "Alexander Raiku"]],
      highlights: ["Succession is designated by the outgoing head of state.", "SRX is the Kingdom's military-technological arm.", "Municipal government continues beneath the national executive."],
      related: ["srx", "arthas-raiku", "alexander-raiku", "midgar"], source: "data/srx_database/factions/SHINRA_KINGDOM.md",
    },
    {
      id: "ria",
      directories: ["institutions"], category: "institutions", title: "Realm Inspection Agency", subtitle: "Sovereign agency headquartered in Cameron City",
      classification: "Foreign Institutional Assessment", ...noImage(),
      summary: "The Realm Inspection Agency is a sovereign security and research power founded to prevent conquest by transnational threats.",
      body: [
        "The RIA was founded by Barron J. Nevermore and Pernos Kail after the destruction of the organization known as the Alliance. Its established departments include technology, medicine, military operations, and espionage.",
        "The agency became the dominant organized power of its period and later fought a ten-year war with SRX. The Treaty of Ceasefire ended open conflict in 3088 CE.",
        "The RIA remains active under Barron Nevermore from Cameron City. It is neither subordinate to Shinra nor designated an active enemy under the present treaty.",
      ],
      facts: [["Founded By", "Barron Nevermore and Pernos Kail"], ["Headquarters", "Cameron City"], ["Current Head", "Barron J. Nevermore"], ["Relation to Shinra", "Sovereign ceasefire partner"]],
      highlights: ["The RIA predates SRX's rise to state power.", "The 3088 CE treaty remains in force.", "Internal RIA capabilities are not represented as confirmed fact without independent verification."],
      related: ["cameron-city", "treaty-of-ceasefire", "srx"], source: "data/srx_database/factions/RIA.md",
    },
    {
      id: "weyr-of-dragonlords",
      directories: ["institutions"], category: "institutions", title: "Weyr of Dragonlords", subtitle: "Independent order seated at Dragon's Keep",
      classification: "Diplomatic Institutional Record", ...noImage(),
      summary: "The Weyr is an independent order of Dragonlords governed from Dragon's Keep by Nexa Rei.",
      body: [
        "A Dragonlord is recorded as a humanoid and dragon soul sharing one existence and capable of manifesting in distinct forms. The order maintains its own customs, command, and territorial authority.",
        "Nexa Rei has presided over Dragon's Keep for more than a century. The Keep's neutrality has been enforced during gatherings attended by members of rival governments.",
        "The Weyr maintains diplomatic relations with Shinra while remaining outside Kingdom command. It is recognized as a sovereign order rather than an SRX affiliate.",
      ],
      facts: [["Seat", "Dragon's Keep"], ["Leader", "Nexa Rei"], ["Jurisdiction", "Independent"], ["Relation to Shinra", "Diplomatic neutrality"]],
      highlights: ["The Weyr answers to no foreign government.", "Dragon's Keep is protected as a treaty zone.", "Neutrality is enforced by the order itself."],
      related: ["dragonskeep", "continental-survey", "shinra-kingdom"], source: "data/srx_database/factions/WEYR_OF_DRAGONLORDS.md",
    },
    {
      id: "adventurers-guild",
      directories: ["institutions"], category: "institutions", title: "Adventurers Guild", subtitle: "Licensed contract clearinghouse of Sector 3",
      classification: "Open Civic Record", ...noImage(),
      summary: "The Adventurers Guild verifies and brokers paid contracts for independent operators working within Midgar law.",
      body: [
        "The Guild operates from Sector 3 near the Market Strip and Exchange Row. It reviews employers, posts available work, and records the completion of sanctioned contracts.",
        "Luma Reed supervises the public contract desk and the registration of new independent operators. Experienced field personnel may be assigned to supervisory or escort duties through Guild agreements.",
        "The Guild is a civilian institution. It operates within the Kingdom but does not form part of SRX command.",
      ],
      facts: [["Location", "Sector 3, Midgar"], ["Function", "Contract verification and brokerage"], ["Public Supervisor", "Luma Reed"], ["Status", "Licensed civilian institution"]],
      highlights: ["Employers are vetted before ordinary contracts are posted.", "Guild registration does not confer SRX rank or clearance.", "Security notices may suspend individual contracts."],
      related: ["merchant-guild", "lower-plate", "midgar"], source: "data/srx_database/factions/ADVENTURERS_GUILD.md",
    },
    {
      id: "merchant-guild",
      directories: ["institutions"], category: "institutions", title: "Merchant Guild", subtitle: "Licensed trade body of Midgar's lower plate",
      classification: "Open Civic Record", ...noImage(),
      summary: "The Merchant Guild represents licensed vendors operating in Midgar's public markets.",
      body: [
        "Guild activity is concentrated in Sector 3, including Market Strip, Exchange Row, and Commons Plaza. Members trade through registered stalls, shops, and mobile licenses.",
        "The Guild is distinct from off-grid markets beneath the city. Its members remain subject to Kingdom commercial law, inspection, and ordinary taxation.",
        "The organization has no military or security authority and maintains a neutral relationship with SRX.",
      ],
      facts: [["Primary District", "Sector 3"], ["Function", "Licensed commercial trade"], ["Jurisdiction", "Shinra Kingdom"], ["Security Role", "None"]],
      highlights: ["Guild affiliation indicates legal commercial registration.", "Individual merchants remain responsible for their own goods and claims.", "Restricted materials require separate authorization."],
      related: ["adventurers-guild", "lower-plate", "midgar"], source: "data/srx_database/factions/MERCHANT_GUILD.md",
    },
    {
      id: "great-rift",
      directories: ["history", "world"], category: "history", title: "The Great Rift", subtitle: "Planetary dimensional collapse of approximately 120 CE",
      classification: "Open Historical Record",
      image: srxAsset("maps/old-map-of-terra.png", "Historic survey map used in comparative studies of prewar Terra."),
      summary: "The Great Rift was a seventy-two-hour collapse of dimensional boundaries that permanently joined Terra to populations and territories from other realities.",
      body: [
        "Tears opened across Terra at continental and urban scale. Gravity, time, physical law, and magical systems behaved unpredictably while multiple realities intersected the planet.",
        "When the Rift closed, displaced populations remained and foreign landscapes had become part of Terra. Population growth, resource scarcity, and conflict followed immediately.",
        "No cause has been demonstrated. Three thousand years of scholarship have produced theories but no evidence sufficient to establish one as fact.",
      ],
      facts: [["Date", "Approximately 120 CE"], ["Duration", "Approximately 72 hours"], ["Scale", "Planetary"], ["Cause", "Unknown"]],
      highlights: ["The Rift permanently altered Terra's population and geography.", "Several incompatible magical systems entered contact at once.", "Official scholarship does not claim a known cause."],
      related: ["the-realm", "terra", "thousand-year-war"], source: "data/lore/world_lore.md",
    },
    {
      id: "thousand-year-war",
      directories: ["history", "world"], category: "history", title: "The 1,000-Year War", subtitle: "The long conflict following the Great Rift",
      classification: "Open Historical Record", ...noImage("No single authenticated image can represent the full thousand-year conflict."),
      summary: "The 1,000-Year War began after the Great Rift and joined territorial, refugee, and Guardian conflicts into a planetary catastrophe.",
      body: [
        "Terra natives and displaced populations fought over land, resources, and surviving pre-Rift knowledge. Refugee factions carried older wars into Terra, while Guardian factions fought over Codex fragments and competing interpretations of their duty.",
        "The Grand Archive, Stone Halls, Great Groves, Coral Throne, and other ancient centers were destroyed. Population declined by an estimated seventy to eighty percent.",
        "The war ended around 1118 CE through exhaustion rather than reconciliation. The ceasefires established territorial boundaries that influenced nearly two thousand years of reconstruction.",
      ],
      facts: [["Approximate Span", "118-1118 CE"], ["Estimated Population Loss", "70-80 percent"], ["Conclusion", "Negotiated ceasefires"], ["Primary Result", "Collapse of ancient institutions"]],
      highlights: ["Most surviving Ai Codian knowledge was lost during the war.", "No single faction achieved victory.", "Modern territorial politics developed from the final military boundaries."],
      related: ["great-rift", "ai-codians", "continental-survey"], source: "data/lore/world_lore.md",
    },
    {
      id: "srx-ria-war",
      directories: ["history"], category: "history", title: "The SRX-RIA War", subtitle: "Ten years of conflict ending in 3088 CE",
      classification: "Declassified Historical Summary", ...noImage("No unrestricted authenticated campaign image is assigned to this summary."),
      summary: "Open conflict between the newly founded SRX and the established Realm Inspection Agency lasted from 3078 to 3088 CE.",
      body: [
        "SRX emerged as a resistance force during a period of RIA dominance. Competition over political authority, security, and technological control escalated into a ten-year war.",
        "Neither institution was destroyed. The conflict ended when both parties signed the Treaty of Ceasefire in 3088 CE and recognized a continuing division of authority.",
        "The treaty transformed military confrontation into guarded coexistence. Cameron City remained under RIA sovereignty while Midgar became the center of Shinra power.",
      ],
      facts: [["Conflict", "3078-3088 CE"], ["Parties", "SRX and RIA"], ["Conclusion", "Treaty of Ceasefire"], ["Present Status", "Ceasefire remains in force"]],
      highlights: ["SRX was founded at the beginning of the conflict.", "The war established the modern balance between Midgar and Cameron City.", "Operational campaign files remain classified by both parties."],
      related: ["srx", "ria", "treaty-of-ceasefire"], source: "data/lore/world_lore.md",
    },
    {
      id: "treaty-of-ceasefire",
      directories: ["history", "institutions"], category: "history", title: "Treaty of Ceasefire", subtitle: "SRX-RIA agreement signed in 3088 CE",
      classification: "Open Treaty Record",
      image: srxAsset("oracle/historical/09-treaty-of-ceasefire.png", "Authenticated archive image of the 3088 CE Treaty of Ceasefire signing."),
      summary: "The Treaty of Ceasefire ended the ten-year war between SRX and the Realm Inspection Agency without dissolving either power.",
      body: [
        "The agreement established a framework for separate sovereignty, controlled diplomatic contact, and the cessation of open military operations.",
        "The treaty did not merge the institutions or resolve their competing political traditions. It created the durable minimum conditions required for reconstruction and trade.",
        "The agreement remains the legal foundation of relations between Midgar and Cameron City in 3120 CE.",
      ],
      facts: [["Signed", "3088 CE"], ["Parties", "SRX and RIA"], ["Outcome", "End of open war"], ["Current Force", "Active"]],
      highlights: ["Both parties retained sovereignty and military capacity.", "Diplomatic trust remains limited.", "The ceasefire has survived later regional conflicts."],
      related: ["srx-ria-war", "srx", "ria", "cameron-city"], source: "data/lore/world_lore.md",
    },
    {
      id: "battle-for-eternium",
      directories: ["history"], category: "history", title: "Battle for Eternium", subtitle: "Tartanalia conflict, 3098-3108 CE",
      classification: "Declassified Historical Summary",
      image: srxAsset("oracle/historical/08-battle-for-eternium-excavation.png", "Authenticated image of the Eternium excavation front during the conflict."),
      summary: "The Battle for Eternium was a decade-long conflict centered on the deposit beneath Tartan Crater.",
      body: [
        "The fall of Tartanalia's barrier in 3013 CE exposed a resource capable of channeling magical energy on an exceptional scale. Competing claims to the deposit grew into armed conflict between 3098 and 3108 CE.",
        "The battle altered the political order surrounding Shinra, Tartanalia, and several independent powers. It was followed by twelve years of reconstruction and institutional consolidation.",
        "The existence, dates, and strategic importance of the conflict are public record. Detailed command decisions, weapons programs, and individual classified operations are not included in this release.",
      ],
      facts: [["Conflict Span", "3098-3108 CE"], ["Primary Site", "Tartan Crater"], ["Strategic Material", "Eternium"], ["Release", "Summary declassified"]],
      highlights: ["The conflict followed the failure of Tartanalia's barrier.", "Eternium remains subject to controlled access.", "Postwar reconstruction reshaped the Shinra state."],
      related: ["tartan-crater", "shinra-kingdom", "srx"], source: "data/srx_database/locations/ETERNIUM.md",
    },
    {
      id: "arthas-raiku",
      directories: ["people"], category: "people", title: "Arthas Raiku", subtitle: "President of the Shinra Kingdom",
      classification: "Executive Public Record",
      image: srxAsset("npc/arthas-raiku.png", "Official portrait of President Arthas Raiku."),
      summary: "Arthas Raiku is President of the Shinra Kingdom and commander-in-chief of Shinra Robotics and Xenogenetics.",
      body: [
        "Born in Midgar in 3102 CE, Raiku entered office in 3120 CE at eighteen years of age, becoming the youngest president in recorded Shinra history.",
        "His office combines head-of-state authority with direct command of SRX. Civilian administration remains under Vice President Alexander Raiku.",
        "The current administration has emphasized continuity of defense, Gateway operations, reconstruction policy, and the integration of government with critical infrastructure.",
      ],
      facts: [["Born", "3102 CE"], ["Office Assumed", "3120 CE"], ["Current Office", "President"], ["Command", "SRX commander-in-chief"]],
      highlights: ["Youngest recorded Shinra president.", "Holds both state and military authority.", "Operates from Shinra Tower, Floor 70."],
      related: ["shinra-kingdom", "srx", "alexander-raiku", "shinra-tower"], source: "data/srx_database/dossiers/ARTHAS_RAIKU_DOSSIER.md",
    },
    {
      id: "alexander-raiku",
      directories: ["people"], category: "people", title: "Alexander Raiku", subtitle: "Vice President and former President of Shinra",
      classification: "Executive Public Record", ...noImage("Official portrait awaits authenticated transfer to the public archive."),
      summary: "Alexander Raiku directs the civilian government and is one of the longest-serving executives in modern Shinra history.",
      body: [
        "Born in 3080 CE, Raiku served as President of the Republic of Shinra through reconstruction and the political transition that followed the Battle for Eternium.",
        "His administration oversaw civilian infrastructure, diplomacy, and the consolidation of public institutions around Midgar. He later transferred the presidency to Arthas Raiku and retained responsibility for civilian administration.",
        "As Vice President, Raiku provides continuity between the former republic and the present Kingdom while remaining outside routine military command.",
      ],
      facts: [["Born", "3080 CE"], ["Current Office", "Vice President"], ["Former Office", "President of the Republic of Shinra"], ["Portfolio", "Civilian administration"]],
      highlights: ["Directed major reconstruction policy.", "Oversaw the transition from republic to kingdom.", "Maintains senior responsibility for diplomatic and civic government."],
      related: ["arthas-raiku", "shinra-kingdom", "zoey-cinclaire"], source: "data/srx_database/dossiers/ALEXANDER_RAIKU_DOSSIER.md",
    },
    {
      id: "zoey-cinclaire",
      directories: ["people", "history"], category: "people", title: "Zoey Cinclaire", subtitle: "Founding Turks officer and reconstruction administrator",
      classification: "Memorial Service Record",
      image: srxAsset("oracle/personnel/portraits/zoey-cinclaire-city.png", "Authenticated memorial portrait of Zoey Cinclaire in Midgar."),
      summary: "Zoey Cinclaire served in the founding modern Turks roster and later held senior responsibilities in urban development and acting command.",
      body: [
        "Cinclaire joined SRX in 3102 CE. Her service expanded from field operations into diplomacy, public coordination, and the reconstruction of Midgar.",
        "During an extended absence in senior leadership, she served as Acting Director and maintained institutional operations across security and civilian departments.",
        "Cinclaire died in 3118 CE. The East Garden memorial at Shinra Tower recognizes her public service and her role in preserving the organization during a period of instability.",
      ],
      facts: [["Joined SRX", "3102 CE"], ["Status", "Deceased, 3118 CE"], ["Known Offices", "Turks; Urban Development; Acting Director"], ["Memorial", "East Garden, Shinra Tower"]],
      highlights: ["Member of the founding modern Turks roster.", "Connected field command with civic reconstruction.", "Maintained SRX operations during a leadership crisis."],
      related: ["alexander-raiku", "shinra-tower", "srx"], source: "data/srx_database/dossiers/ZOEY_CINCLAIRE_DOSSIER.md",
    },
    {
      id: "ayame-silveredge",
      directories: ["people", "history"], category: "people", title: "Ayame Silveredge", subtitle: "Historic security officer and diplomatic protector",
      classification: "Public Service Extract",
      image: srxAsset("npc/Ayame.png", "Authenticated public archive portrait of Ayame Silveredge."),
      summary: "Ayame Silveredge, recorded in earlier files as Xeria Silveredge, served across multiple periods of Shinra security and diplomatic protection.",
      body: [
        "Silveredge's public service includes special operations, intelligence work, and executive protection. Her assignments placed her alongside senior Shinra personnel during negotiations and regional security operations.",
        "She served as diplomatic protector to Alexander Raiku and contributed to early standards for field intelligence and executive security.",
        "Several identities associated with later operations remain restricted. This record acknowledges established public service without disclosing active methods, locations, or protected persons.",
      ],
      facts: [["Public Name", "Ayame Silveredge"], ["Historic Archive Name", "Xeria Silveredge"], ["Known Service", "Special operations and executive protection"], ["Status", "Operational details restricted"]],
      highlights: ["Served across multiple generations of Shinra leadership.", "Held diplomatic protection assignments.", "Later covert activity is excluded from public release."],
      related: ["alexander-raiku", "zoey-cinclaire", "srx"], source: "data/srx_database/dossiers/XERIA_SILVEREDGE_DOSSIER.md",
    },
    {
      id: "sephiroth-raiku",
      directories: ["people", "history"], category: "people", title: "Sephiroth Raiku", subtitle: "Founder of SRX and early Shinra executive",
      classification: "Declassified Executive History", ...noImage("Historic portrait awaits authenticated transfer to the public archive."),
      summary: "Sephiroth Raiku founded the organization that became Shinra Robotics and Xenogenetics and directed its early expansion in Midgar.",
      body: [
        "Born Sephiroth Makai, he survived displacement and conflict in Silvermoon before entering the protection and training of the Silveredge household.",
        "Raiku organized Shinra Resurrected X in 3078 CE from the remains of an earlier Shin-Ra government. Working with Chaz Asheline and the first command circle, he developed the organization into a major source of defense, employment, and technical capacity.",
        "His presidency established structures later inherited by the Shinra state. Individual experimental programs and final wartime operations remain outside this declassified history.",
      ],
      facts: [["Known Names", "Sephiroth Makai; Sephiroth Raiku"], ["Historic Office", "Founder and President"], ["Organization Founded", "Shinra Resurrected X"], ["Founding Year", "3078 CE"]],
      highlights: ["Established the first SRX command structure.", "Expanded Shinra employment and industry in Midgar.", "Several operational files remain classified."],
      related: ["srx", "srx-ria-war", "shinra-kingdom"], source: "The Realm Historical Archive/Rp Post/seph bio.txt",
    },
  ],
};
